---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/operations_imported_stores/index":
    parameters:
    - name: store
      in: query
      description: name store
      required: true
      schema:
        type: string
    get:
      summary: list stores
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000