default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cnab_bybcoders_development
  username: postgres
  password: postgres
  host: db
  port: 5432
  
test:
  <<: *default
  database: cnab_bybcoders_test
  username: postgres
  password: postgres
  host: db
  port: 5432

production:
  <<: *default
  database: cnab_bybcoders_production
  username: cnab_bybcoders
  password: <%= ENV["CNAB_BYBCODERS_DATABASE_PASSWORD"] %>
